src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $post;

    public function __construct(Post $post, $user = null)
    {
        $this->published_date = new \DateTime() ? new \DateTime() : 'NEW';
        $this->post= $post;
        $this->author = $user;
    }

    public function __toString()
    {
        return $this->content;
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->published_date;
    }

    public function setPublishedDate(\DateTimeInterface $publised_date): self
    {
        $this->published_date = $published_date;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $preview;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="posts")
     * @Assert\NotBlank()
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="posts")
     * @Assert\NotBlank()
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post")
     */
    private $comments;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->published_at = new \DateTime() ? new \DateTime() : 'NEW';
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getPreview(): ?string
    {
        return $this->preview;
    }

    public function setPreview(string $preview): self
    {
        $this->preview = $preview;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\PostsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\Entity\Post;
use App\Entity\Category;
use App\Entity\Tag;
use App\Entity\Comment;
use App\Entity\User;
use App\Form\CommentType;
use App\Repository\CategoryRepository;
use App\Repository\TagRepository;
use App\Repository\PostRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Psr\Log\LoggerInterface;
use App\Service\CommentManager;
use App\Service\DeleteManager;

class MainController extends Controller
{
    /**
     * @Route("/posts", name="posts")
     */
    public function posts(Request $request, PostRepository $postRepository)
    {   
        // create pagination
        $posts = $postRepository->findAll();

        $pagination = $this->get('knp_paginator')->paginate(
            $posts,
            $request->query->getInt('page', 1),
            3
        );
        $pagination->setTemplate('@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig');

        return $this->render('main/posts.html.twig', ['pagination' => $pagination]);
    }

    /**
     * @Route("/posts/{id}", name="showPostById", requirements={"id"="\d+"})
     */
    public function showPostById(Post $post)
    {   
        $form = $this->get(CommentManager::class)->createFormComment($post);

        return $this->render('main/post.html.twig', [
            'post' => $post,
            'form' => $form
            ]
        );
    }

    /**
     * @Route("/posts/{id}/heart", name="togglePostHeart", requirements={"id"="\d+"}, methods={"POST"})
     */ 
    public function togglePostHeart()
    {
        return $this->json(['hearts' => rand(5, 100)]);
    }

    /**
     * @Route("posts/{id}/comments/save", name="saveComment")
     */
    public function saveComment(Post $post, Request $request, LoggerInterface $logger)
    {
        $user = $this->getUser();
        $comment = $this->get(CommentManager::class)->saveCommentToDb($request, $post, $user);

        //if comment create
        if (!$comment) {
            //show flash message
            $message = 'You add a new comment!';
            $this->addFlash('success', $message);
            //create log message
            $logger->info($message);

            return $this->redirectToRoute('showPostById', ['id' => $post->getId()]);
        }
    }
    /**
     * @Route("posts/{id}/comments/{commentId}/delete", name="deleteComment")
     * @ParamConverter("comment", options={"mapping": {"commentId" = "id"}})
     */
    public function deleteComment(Comment $comment, Post $post, LoggerInterface $logger)
    {
        //remove comment from database
        $result = $this->get(DeleteManager::class)->deleteItemFromDB($comment);

        if ($result) {
            //show flash message
            $message = 'You delete a comment!';
            $this->addFlash('success', $message);

            //create log message
            $logger->info($message);
        }        

        return $this->redirectToRoute('showPostById', ['id' => $post->getId()] );
    }
  
}

templates/main/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    <div class="col-md-12">
        {{ form_row(form.content) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.author) }}
    </div>
    <button class="btn btn-info">{{ button_label|default('Comment') }}</button>
{{ form_end(form) }}

templates/main/post.html.twig
{% extends 'base/base.html.twig' %}

{% block content %}

{% block fleshMessage %}
    {{ parent() }}
{% endblock %}

<div class="container">
    <div class="row">

        <div class="col-sm-12 col-md-8">
            <div class="show-article-container p-3 mt-4">
                <div class="row">
                    <div class="col-sm-12">
                        <img class="show-article-img" src="{{ asset(post.preview) }}">
                        <div class="show-article-title-container d-inline-block pl-3 align-middle">
                            <span class="show-article-title ">{{ post.title|title }}</span>
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">{{ post.author }}</span>
                            <span class="pl-2 article-details">{{ post.publishedAt|date("d.m.Y G:i:s") }}</span>
                            <span class="pl-2 article-details">
                                <span class="js-like-article-count">5<span>
                                <a href="{{ path('togglePostHeart', {'id': post.id}) }}" class="fa fa-heart-o like-article js-like-article"></a>
                            </span>
                            
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="article-text">
                            <p>{{ post.content }}</p>
                            <p><a href="{{ path('showPostsByCategory', {'category': post.category.name}) }}" >Back to catecory: {{ post.category }}</a></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i></p>
                    </div>
                </div>
                
                {# shows comments for unauthorized users, can not add a comment #} 
                {% if app.user is empty %}

                <div class="row">
                    <div class="col-sm-12">

                    {% if post.comments is empty %}

                        <h3><i class="pr-3 fa fa-comment"></i>No comments</h3><hr>

                    {% else %}

                        <h3><i class="pr-3 fa fa-comment"></i>{{ post.comments|length }} comments</h3><hr>
                        <div class="row">

                        {% for comment in post.comments %}
                        
                            <div class="col-sm-12">
                                <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                                <div class="comment-container d-inline-block pl-3 align-top">
                                    <span class="align-left commenter-name">{{ comment.author }}</span>
                                    <span class="align-right comment">{{ comment.publishedDate|date("d.m.Y G:i:s") }}</span>
                                    <br>
                                    <p class="comment">{{ comment.content }}</p>
                               </div><hr>
                            </div>

                        {% endfor %}

                        </div>

                    {% endif %}

                    </div>
                </div>

                {% else %}
                {# shows comments for authorized users, can add a comment #} 
                <div class="row">
                    <div class="col-sm-12">

                    {% if post.comments is empty %}

                        <h3><i class="pr-3 fa fa-comment"></i>No comments</h3><hr>
                        <h3>Add new comment</h3>
                        {{ include('main/partial/_form.html.twig') }}

                    {% else %}

                        <h3><i class="pr-3 fa fa-comment"></i>{{ post.comments|length }} comments</h3><hr>
                        <div class="row">

                        {% for comment in post.comments %}
                            
                            <div class="col-sm-12">
                                <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                                <div class="comment-container d-inline-block pl-3 align-top">
                                    <span class="align-left commenter-name">{{ comment.author }}</span>
                                    <span class="align-right comment">{{ comment.publishedDate|date("d.m.Y G:i:s") }}</span>
                                    <br>
                                    <p class="comment">{{ comment.content }}</p>
                                </div>
                                <div class="comment-container" >
                                    <a href="{{ path('deleteComment', {'id': post.id, 'commentId': comment.id}) }}">
                                        <button class="btn btn-danger">Delete</button>
                                    </a><hr><br>
                                </div>
                            </div>

                        {% endfor%}

                        </div>
                        <h3>Add new comment</h3>
                        {{ include('main/partial/_form.html.twig') }}
                        
                        {% endif %}                      

                    </div>
                </div>                    

                {% endif %}    
                
            </div>
        </div>
        
        <!-- Right bar ad space -->
        {% block rightBar %}
            {{ parent() }}            
        {% endblock %}
        
    </div>
</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/articleShow.js') }}"></script>
{% endblock %}

templates/main/posts.html.twig
{% extends 'base/base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    <link rel="stylesheet" href="{{ asset('css/font-awesome.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            
            <!-- Article List -->

            <div class="col-sm-12 col-md-8">                                   

                {% for post in pagination %}

                <div class="article-container my-1">
                    <a href="{{ path('showPostById', {'id': post.id}) }}">
                        <img class="article-img" src="{{ asset(asset(post.preview)) }}">
                        <span>{{ post.title|title }}</span>
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <hr>
                            <span>{{ post.description|title }}</span>
                            <hr>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">{{ post.author }}</span>                                
                        </div>
                    </a>
                    <hr>
                    <div>
                        {# <a href="{{ path('category_show', {'id': post.category.id}) }}" class="align-right article-details btn-info">{{ post.category }}</a> #}
                        {% for tag in post.tags %}

                            <a href="{{ path('showPostsByTag', {'tag': tag.name}) }}" class="align-right article-details btn-warning">{{ tag.name }}</a>

                        {% endfor %}

                        <p class="pl-5 article-details float-right">{{ post.publishedAt|date("d.m.Y G:i:s") }}</p><br>
                    </div>
                </div>

                {% endfor %}

            </div>       

            <!-- Right bar ad space -->
            {% block rightBar %}
                {{ parent() }}            
            {% endblock %}

        </div>
        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>

    

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/showCategories.js') }}"></script>
{% endblock %}